spring:
  datasource:
    url: jdbc:mysql://localhost:3306/runoob?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
server:
  servlet:
    context-path: /web4
  port: 8080
---
## 对象注入测试
user:
  username: 邹芳${random.uuid}
  age: 15${random.int(20)}
  date: 2019/12/12
  map: {username: zoufang,userage: 45}
  list:
    - list1
    - list2
  filelist:
    name: jsp
    url: http://
    res: 0